//
// Created by dell on 06.03.2018.
//

#ifndef JIMP_EXERCISES_MULTIPLICATIONTABLE_H
#define JIMP_EXERCISES_MULTIPLICATIONTABLE_H

void MultiplicationTable(int tab[][10]);


#endif //JIMP_EXERCISES_MULTIPLICATIONTABLE_H
